//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libSimba.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("libSimba.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;swagger&quot;: &quot;2.0&quot;,
        ///  &quot;info&quot;: {
        ///    &quot;title&quot;: &quot;SimbaChainChain API V1&quot;,
        ///    &quot;description&quot;: &quot;A description of this API goes here.&quot;,
        ///    &quot;termsOfService&quot;: &quot;https://www.simbachain.com/policies/terms/&quot;,
        ///    &quot;contact&quot;: {
        ///      &quot;email&quot;: &quot;contact@simbachain.com&quot;
        ///    },
        ///    &quot;license&quot;: {
        ///      &quot;name&quot;: &quot;&quot;,
        ///      &quot;url&quot;: &quot;https://www.simbachain.com/policies/licence&quot;
        ///    },
        ///    &quot;version&quot;: &quot;v1&quot;,
        ///    &quot;x-simba-attrs&quot;: {
        ///      &quot;api_name&quot;: &quot;libSimbaChain-SimbaChainChat-Quorum&quot;,
        ///      &quot;faucet&quot;: null,
        ///      &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string simbachat_swagger_json {
            get {
                return ResourceManager.GetString("simbachat.swagger.json", resourceCulture);
            }
        }
    }
}
